baseURL = "https://research.ukhsa.gov.uk/"
languageCode = "en-us"
title = "UK Health Security Agency"
theme = "phe"

[menu]
  [[menu.main]]
    name = "About research"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Our research"
    url = "/our-research/"
    identifier = "our-research"
    weight = 2
  [[menu.main]]
    name = "Our research"
    url = "/our-research/"
    parent = "our-research"
    weight = 3
  [[menu.main]]
    name = "Partnerships"
    url = "/partnerships/"
    weight = 4
  [[menu.main]]
    name = "Research opportunities"
    url = "/opportunities/"
    weight = 5
  [[menu.main]]
    name = "awerb"
    url = "/awerb/"
    weight = 6
  [[menu.main]]
    name = "Research integrity"
    url = "/research-integrity/"
    weight = 7
  [[menu.main]]
    name = "Contact us"
    url = "/contact/"
    weight = 8
#  [[menu.main]]
#    name = "Divisions"
#    url = "/divisions/"
#    parent = "our-research"
#    weight = 9
